import os
from groq import Groq
from dotenv import load_dotenv

load_dotenv()

client = Groq(api_key=os.environ.get("GROQ_API_KEY"))

SYSTEM_PROMPT = """You are an expert at detecting whether text was written by a human or generated by AI.

Analyze the submitted text and return ONLY a JSON object with this exact structure:
{
  "score": <float between 0.0 and 1.0>,
  "reasoning": "<one sentence>"
}

Score meaning:
- 0.0 = almost certainly human-written
- 1.0 = almost certainly AI-generated

Look for: overly uniform sentence structure, transitional phrases like "furthermore" or "it is important to note", 
lack of personal voice, unnaturally consistent paragraph length, and hedged generic language.
Return ONLY the JSON object. No preamble, no explanation, no markdown fences."""

def groq_score(text: str) -> dict:
    """
    Returns {"score": float, "reasoning": str}
    score: 0.0 (human) to 1.0 (AI)
    """
    response = client.chat.completions.create(
        model="llama-3.3-70b-versatile",
        messages=[
            {"role": "system", "content": SYSTEM_PROMPT},
            {"role": "user", "content": f"Analyze this text:\n\n{text}"}
        ],
        temperature=0.1,
        max_tokens=200,
    )

    raw = response.choices[0].message.content.strip()

    import json
    try:
        result = json.loads(raw)
        score = float(result.get("score", 0.5))
        score = max(0.0, min(1.0, score))  # clamp to [0, 1]
        return {
            "score": round(score, 4),
            "reasoning": result.get("reasoning", "No reasoning provided.")
        }
    except (json.JSONDecodeError, ValueError):
        return {"score": 0.5, "reasoning": "Parse error — defaulting to uncertain."}


# Quick test — run this file directly: python signals/llm_signal.py
if __name__ == "__main__":
    tests = [
        ("AI test", "Artificial intelligence represents a transformative paradigm shift in modern society. It is important to note that while the benefits are numerous, stakeholders must collaborate to ensure responsible deployment."),
        ("Human test", "ok so i finally tried that new ramen place downtown and honestly? underwhelming. the broth was fine but they put WAY too much sodium in it and i was thirsty for like three hours after."),
    ]
    for label, text in tests:
        result = groq_score(text)
        print(f"\n[{label}]")
        print(f"  Score: {result['score']}")
        print(f"  Reasoning: {result['reasoning']}")